apiVersion: 1

datasources:
  - name: Salmonicultura SQLite
    uid: salmonicultura_sqlite
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      path: /var/lib/grafana/sqlite/salmonicultura.db